site_name: INDICAA
theme: 
  icon:
    repo: fontawesome/brands/github-square
  name: material
  custom_dir: overrides
  logo: assets/images/logo.svg
  favicon: assets/images/logo.svg
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - mkdocstrings:
      watch:
        - overrides
repo_url: https://github.com/fga-eps-mds/2021.2-INDICAA