site_name: INDICAA
theme: 
  icon:
    repo: fontawesome/brands/github-square
  name: material
  custom_dir: overrides
  logo: assets/images/logo.svg
  favicon: assets/images/logo.svg
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - mkdocstrings:
      watch:
        - overrides
repo_url: https://github.com/fga-eps-mds/2021.2-INDICAA